services:
  mkv-chapter-backup:
    build: .
    container_name: mkv-chapter-backup
    ports:
      - "8077:8000"
    volumes:
      - ./data:/data
      - ./test:/libraries
    environment:
      - DB_PATH=/data/chapters.db
      - LIBRARIES_ROOT=/libraries
    restart: unless-stopped
